"""
SRIE Refactor Agent v0.1
Automated Refactoring & Safe Execution Module

Reads Plans generated by Planner, applies changes to config/code,
runs validation tests, and rolls back on failure.
"""

import os
import sys
import json
import shutil
import subprocess
import argparse
from datetime import datetime

class RefactorAgent:
    def __init__(self, plan_path, dry_run=False):
        self.plan_path = plan_path
        self.dry_run = dry_run
        self.base_dir = os.path.dirname(os.path.abspath(__file__))
        self.report = {
            "plan_id": "",
            "executed_at": "",
            "mode": "DRY_RUN" if dry_run else "EXECUTION",
            "results": []
        }
        
        try:
            with open(self.plan_path, 'r') as f:
                self.plan = json.load(f)
            self.report["plan_id"] = self.plan.get("plan_id", "UNKNOWN")
        except Exception as e:
            print(f"❌ Error loading plan: {e}")
            sys.exit(1)

    def _backup_file(self, filepath):
        """Backup target file to backups/ directory"""
        backup_dir = os.path.join(self.base_dir, "backups")
        os.makedirs(backup_dir, exist_ok=True)
        filename = os.path.basename(filepath)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = os.path.join(backup_dir, f"{timestamp}_{filename}")
        shutil.copy2(filepath, backup_path)
        print(f"💾 Backed up {filepath} -> {backup_path}")
        return backup_path

    def _update_config(self, action):
        """Update JSON config file with dot-notation keys"""
        target_file = os.path.join(self.base_dir, action["file"])
        if not os.path.exists(target_file):
            raise FileNotFoundError(f"Target file not found: {target_file}")

        backup_path = self._backup_file(target_file)
        
        with open(target_file, 'r') as f:
            config = json.load(f)

        # Handle dot notation (e.g. "thresholds.trust")
        keys = action["key"].split(".")
        current = config
        for k in keys[:-1]:
            current = current.get(k, {})
        
        old_value = current.get(keys[-1])
        current[keys[-1]] = action["new_value"]
        
        with open(target_file, 'w') as f:
            json.dump(config, f, indent=2)
            
        print(f"✅ Modified {action['key']}: {old_value} -> {action['new_value']}")
        return backup_path

    def _run_tests(self, test_command):
        """Run test command and return (success, stdout, stderr)"""
        print(f"🧪 Running test: {test_command}")
        try:
            result = subprocess.run(
                test_command, 
                shell=True, 
                cwd=self.base_dir, 
                capture_output=True, 
                text=True,
                timeout=60
            )
            return result.returncode == 0, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return False, "", "Test execution timed out (60s)"
        except Exception as e:
            return False, "", str(e)

    def execute(self):
        self.report["executed_at"] = datetime.now().isoformat()
        
        if self.dry_run:
            print("🔍 DRY RUN MODE: No changes will be made.")
            for action in self.plan.get("actions", []):
                print(f"   -> Would apply {action['type']} to {action['file']}")
                print(f"      Key: {action['key']} = {action['new_value']}")
            return

        for action in self.plan.get("actions", []):
            action_result = {
                "action": action,
                "status": "SKIPPED",
                "output": ""
            }
            
            if action["type"] != "UPDATE_CONFIG":
                action_result["output"] = f"Unsupported action type: {action['type']}"
                self.report["results"].append(action_result)
                continue

            try:
                # 1. Apply Change
                backup_path = self._update_config(action)
                
                # 2. Verify
                success, stdout, stderr = self._run_tests(action["test_command"])
                
                if success:
                    action_result["status"] = "SUCCESS"
                    action_result["output"] = "Tests passed."
                else:
                    action_result["status"] = "FAILED"
                    action_result["output"] = f"Tests failed.\n{stderr}"
                    
                    # 3. Rollback
                    print(f"❌ Tests failed! Rolling back {action['file']}")
                    shutil.copy2(backup_path, os.path.join(self.base_dir, action["file"]))
                    action_result["output"] += " (Rolled back)"

            except Exception as e:
                action_result["status"] = "FAILED"
                action_result["output"] = str(e)

            self.report["results"].append(action_result)
        
        # Save execution report
        reports_dir = os.path.join(self.base_dir, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        report_path = os.path.join(reports_dir, f"exec_report_{self.report['plan_id']}.json")
        
        with open(report_path, 'w') as f:
            json.dump(self.report, f, indent=2)
        print(f"📝 Execution report saved to: {report_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", type=str, required=False, help="Path to plan JSON")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode")
    args = parser.parse_args()

    # Auto-detect latest plan
    if not args.plan:
        plans_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plans")
        plans = [f for f in os.listdir(plans_dir) if f.endswith('.json')]
        if not plans:
            print("❌ No plans found.")
            sys.exit(1)
        plans.sort(reverse=True)
        args.plan = os.path.join(plans_dir, plans[0])

    agent = RefactorAgent(args.plan, dry_run=args.dry_run)
    agent.execute()